server:
  port: 8080

spring:
  # .env 파일 찾아서 읽기
  config:
    import: optional:file:backend/.env[.properties]
  
  # 데이터베이스 연결 설정 (MySQL)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # 이메일 인증 설정 (Google SMTP)

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: false
            trust: smtp.gmail.com
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  # 파일 업로드 설정 (퀴즈 이미지용)
  servlet:
    multipart:
      max-file-size: 10MB      # 파일 하나당 최대 크기
      max-request-size: 10MB   # 한 번 요청의 최대 크기

# MyBatis 설정
mybatis:
  mapper-locations: classpath:mapper/**/*.xml  # xml 위치
  type-aliases-package: com.problemio.**.domain  # DTO 위치로 바꿀것
  configuration:
    map-underscore-to-camel-case: true
    # MyBatis 로그를 콘솔에 찍기
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# JWT 설정
jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000 # 1시간

# 로깅 레벨 설정
logging:
  level:
    root: info
    com.problemio: debug
